# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 877ba6d
_src_path: gh:tfriedel/python-copier-template
author_email: thomas.friedel@gmail.com
author_name: Thomas Friedel
description: Python tool to extract data from Asana
package_name: asana_exporter
project_name: asana-exporter
python_version: '3.13'
